### ISSUE TITLE
Cannot import tensorflow_probability

### ISSUE THREAD

**Issue by michalisfrangos** [tensorflow/probability#24]
Hello, 

Unfortunately, I cannot import tensorflow_probability, and I get the error below, which I thought to report, as I cannot get around this.  Any suggestions much appreciated..

I am using a Windows PC, and have created a python 3.5 environment, installed the latest version of tensorflow (1.7), and then installed the latest version of tensorflow probability following the installation instructions [here](https://github.com/tensorflow/probability/blob/master/README.md) .

```
\Users\myname\AppData\Roaming\Python\Python35\site-packages\tensorflow\python\util\tf_inspect.py:45:
 DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
```

Best, 
M

**Comment by csuter** [comment]
Hi Michalis, thanks for notifying us of this; we will look into it on our side.

Meanwhile, it looks like the error comes from TF core code -- can you confirm you are able to successfully import tensorflow?

**Comment by michalisfrangos** [comment]
Hi csuter, 

Thanks for the reply. I confirm that I am able to import tensorflow  successfully .

Thanks, 
M

**Comment by csuter** [comment]
Thanks for confirming, Michalis. It looks to me like this is only a warning -- so things *should* still work, despite the noisy messages. Please let us know if you're not able to run code using tensorflow_probability at all (in my testing, it seems to work fine, but my system/setup may be different).

Meanwhile, we will raise this with the TF core team to see about getting the deprecated code cleaned up.

**Comment by michalisfrangos** [comment]
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-6edeb441dd3f> in <module>()
     18 pdf = GaussianCopulaTriL(
     19     loc=[0., 0.],
---> 20     scale_tril=[[1., 0.8], [0., 0.6]],
     21 ).prob(coordinates)

<ipython-input-3-6edeb441dd3f> in __init__(self, loc, scale_tril)
      6             loc=loc,
      7             scale_tril=scale_tril),
----> 8         bijector=tfb.Invert(NormalCDF()),
      9         validate_args=False,
     10         name="GaussianCopulaTriLUniform")

<ipython-input-2-51fa940429dd> in __init__(self)
     13         forward_min_event_ndims=0,
     14         validate_args=False,
---> 15         name="NormalCDF")
     16 
     17   def _forward(self, y):

TypeError: __init__() got an unexpected keyword argument 'forward_min_event_ndims'
```

**Comment by srvasude** [comment]
Hi Michalis,
   Currently Tensorflow Probability is dependent on tf-nightly. There was a change to tensorflow with the bijector API (that is only in nightly), and so I think updating to tf-nightly should resolve the issue you see.

**Comment by michalisfrangos** [comment]
Hi Srinivas,Christopher, 

Thanks for your responses.  Coming back to this after a couple of few weeks, I have created a new environment python 3.5 envirnonment and installed tensorflow probability following your instructions. I am able to import tensorflow_probability, and I can run the notebooks: 
- Eight_Schools
- Understanding TensorFlow Distributions Shapes

However, I cannot run Gaussian_Copula  getting exactly the same error as above 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-30196978ccf1> in <module>()
     20 pdf = GaussianCopulaTriL(
     21     loc=[0., 0.],
---> 22     scale_tril=[[1., 0.8], [0., 0.6]],
     23 ).prob(coordinates)
     24 

<ipython-input-10-30196978ccf1> in __init__(self, loc, scale_tril)
      6             loc=loc,
      7             scale_tril=scale_tril),
----> 8         bijector=tfb.Invert(NormalCDF()),
      9         validate_args=False,
     10         name="GaussianCopulaTriLUniform")

<ipython-input-8-51fa940429dd> in __init__(self)
     13         forward_min_event_ndims=0,
     14         validate_args=False,
---> 15         name="NormalCDF")
     16 
     17   def _forward(self, y):

TypeError: __init__() got an unexpected keyword argument 'forward_min_event_ndims'
```

and I cannot run the notebook Linear_Mixed_Effects_Models, getting an error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-26e12e3c9108> in <module>()
     24 
     25 current_state = [effect_students, effect_instructors, effect_departments]
---> 26 with warnings.catch_warnings(UserWarning):
     27   # TensorFlow raises a warning about converting sparse IndexedSlices to a
     28   # dense Tensor during gradient computation. This can consume a large amount

TypeError: __init__() takes 1 positional argument but 2 were given
```
I don't believe I am doing something wrong in the installation process, therefore I thought to mention this to you again. 

Many thanks, 
Michalis

**Comment by srvasude** [comment]
Thanks Michalis.

This is very odd indeed.

Here's my set of commands:

pip3 uninstall tensorflow  **tf-nightly**  # Latest version will automatically be installed by tfp-nightly.
pip3 install --user  --upgrade **tfp-nightly**

How are you running the notebooks, so I can try to reproduce?

**Comment by michalisfrangos** [comment]
Hi Srinivas, 

I have removed all anaconda, python  related programs, and installed a clean miniconda, latest tensorflow following your instructions. I still cannot import things properly, but this time I have soe idea why. And glad to see that this is related to another post [here](https://github.com/tensorflow/probability/issues/39). #39 

It seems that when we try to import tensorflow_probability, it is trying to impotr things from 
`C:\Users\myname\AppData\Roaming` and some packages are simply not there, like seed_stream.py

```
~\AppData\Roaming\Python\Python35\site-packages\tensorflow_probability\python\mcmc\langevin.py in <module>()
     28 from tensorflow_probability.python.mcmc import util as mcmc_util
     29 
---> 30 from tensorflow.contrib.distributions.python.ops import seed_stream
     31 from tensorflow.python.ops.distributions import util as distributions_util
     32 

Import Error: cannot import name 'seed_stream'
```

However, seed_stream is in a different location under local. 
`C:\Users\myname\AppData\Local\Continuum\miniconda3\envs\tensorflow_1p8\Lib\site-packages\tensorflow\contrib\distributions\python\ops`


And to answer your questions, I am running Jupyter-notebook from the prompt which I have activated my environment which tensorflow is installed. As I mentioned above, I have no other environment, and followed instructions by letter for installing tensorflow-probability... 

That's all I have for now, and not clear how to solve the issue.

Thanks, Michalis

**Comment by srvasude** [comment]
Thanks for the details. I'll consolidate discussion on the other post.

**Comment by gaceladri** [comment]
Same here,

`TypeError                                 Traceback (most recent call last)
<ipython-input-24-30196978ccf1> in <module>()
     20 pdf = GaussianCopulaTriL(
     21     loc=[0., 0.],
---> 22     scale_tril=[[1., 0.8], [0., 0.6]],
     23 ).prob(coordinates)
     24 

<ipython-input-24-30196978ccf1> in __init__(self, loc, scale_tril)
      6             loc=loc,
      7             scale_tril=scale_tril),
----> 8         bijector=tfb.Invert(NormalCDF()),
      9         validate_args=False,
     10         name="GaussianCopulaTriLUniform")

<ipython-input-23-0f9a77b39622> in __init__(self)
     13             forward_min_event_ndims=0,
     14             validate_args=False,
---> 15             name="NormalCDF")
     16 
     17     def _forward(self, y):

TypeError: __init__() got an unexpected keyword argument 'forward_min_event_ndims'
`

when trying to execute the copulas notebook.
Freshly installed conda environment with tf, tf-nigtly and so on. python 3.5, tensorflow 1.8 with gpu

Regards
